CREATE TABLE usuario (uid int(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                      usuario varchar(60) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                      senha varchar(60) NOT NULL);
                      
CREATE TABLE grafico (id int(20) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
					  uid_usuario int(20) NOT NULL,	
                      nome_grafico varchar(60) NOT NULL,
                      eixo_y varchar(60) NOT NULL,
                      id_serie int(20) NOT NULL,
                      serie varchar(60) NOT NULL);                   